# Config file for autoencoder training

dataset_params:
  dataset_dir: 'resources/data' # Path to dataset passed into SpectrogramDataset
  nbars: 4
  im_channels : 4
  im_size : 512
  num_workers_ds : 4 # Number of workers for loading the dataset

autoencoder_params:
  z_channels: 4
  codebook_size : 8192
  down_channels : [64, 128, 256, 256]
  mid_channels : [256, 256]
  down_sample : [True, True, True]
  attn_down : [False, False, False]
  norm_channels: 32
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2

train_params:
  seed : 1943
  ckpt_base_dir: 'resources/train/ckpts'
  autoencoder_batch_size: 4
  disc_start: 15000     # Start training discriminator after this many steps
  disc_weight: 0.5      # Weight of discriminator loss
  codebook_weight: 1    # Weight of codebook loss
  commitment_beta: 0.2
  perceptual_weight: 1
  epochs: 20
  autoencoder_lr: 0.00001
  autoencoder_acc_steps: 4
  autoencoder_img_save_steps: 64
  vqvae_autoencoder_ckpt_name: 'vqvae_autoencoder_ckpt.pth'
  vqvae_discriminator_ckpt_name: 'vqvae_discriminator_ckpt.pth'
